function money(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0)}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function postJSON(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Request failed');return d}
function renderResult(d){const root=document.getElementById('result');root.innerHTML=`<section class="panel"><p class="eyebrow">${d.ai_generated?'AI GENERATED':'FALLBACK PLAN'}</p><h2>${escapeHtml(d.title)}</h2><p>${escapeHtml(d.summary)}</p><p><b>Estimated total:</b> ${money(d.total_estimated)} &nbsp; <b>Remaining:</b> ${money(d.budget_remaining)}</p>${d.warning?`<p class="muted">${escapeHtml(d.warning)}</p>`:''}<h3>Budget allocation</h3>${(d.allocations||[]).map(a=>`<div class="allocation"><span>${escapeHtml(a.category)}</span><b>${money(a.amount)} (${a.percentage.toFixed(0)}%)</b></div>`).join('')}<h3>Recommendations</h3><div class="result-grid">${(d.recommendations||[]).map(x=>`<article class="result-item"><h3>${escapeHtml(x.name)}</h3><p class="muted">${escapeHtml(x.category)} · ${escapeHtml(x.platform)}</p><p class="price">${money(x.estimated_price)} × ${x.quantity}</p><p>${escapeHtml(x.reason)}</p><a href="${x.search_url}" target="_blank" rel="noopener">Search on ${escapeHtml(x.platform)} →</a></article>`).join('')}</div><h3>Tips</h3><ul>${(d.tips||[]).map(t=>`<li>${escapeHtml(t)}</li>`).join('')}</ul></section>`}
function addHomeItem(){const box=document.getElementById('home-items');const row=document.createElement('div');row.className='item-row';row.innerHTML='<input placeholder="e.g. Ceiling fan" required><input type="number" min="1" value="1" required><button type="button" aria-label="Remove">×</button>';row.querySelector('button').onclick=()=>row.remove();box.appendChild(row)}
async function submitHome(e){e.preventDefault();const rows=[...document.querySelectorAll('#home-items .item-row')];const body={budget:Number(document.getElementById('budget').value),rooms:[...document.getElementById('rooms').selectedOptions].map(x=>x.value),style:document.getElementById('style').value,location:document.getElementById('location').value,items:rows.map(r=>({category:r.children[0].value,quantity:Number(r.children[1].value)}))};try{renderResult(await postJSON('/api/generate-home',body))}catch(err){alert(err.message)}}
async function submitParty(e){e.preventDefault();const body={budget:Number(document.getElementById('budget').value),guests:Number(document.getElementById('guests').value),event_type:document.getElementById('event_type').value,venue:document.getElementById('venue').value||'Flexible',city:document.getElementById('city').value,preferences:document.getElementById('preferences').value};try{renderResult(await postJSON('/api/generate-party',body))}catch(err){alert(err.message)}}
async function submitJewelry(e){e.preventDefault();const form=new FormData(e.target);try{const r=await fetch('/api/generate-jewelry',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Request failed');renderResult(d)}catch(err){alert(err.message)}}
async function loadHistory(){const root=document.getElementById('history');try{const r=await fetch('/api/history');const d=await r.json();if(!r.ok)throw new Error(d.detail||'Unable to load history');root.innerHTML=d.length?d.map(x=>`<article class="history-card"><b>${escapeHtml(x.planner.toUpperCase())}</b><h3>${escapeHtml(x.response.title)}</h3><p>${escapeHtml(x.response.summary)}</p><p class="muted">${escapeHtml(x.created_at)} · ${money(x.response.total_estimated)}</p></article>`).join(''):'<div class="panel"><p>No saved recommendations yet.</p></div>'}catch(e){root.innerHTML=`<div class="panel">${escapeHtml(e.message)}</div>`}}
